name: docker-build
run-name: docker-build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        env: 
          ARTIFACTORY_JSON: "${{ secrets.ARTIFACTORY_JSON }}"
        run: |- 
             echo ${ARTIFACTORY_JSON} | docker login -u _json_key --password-stdin https://asia-south1-docker.pkg.dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Container
        run: |- 
             docker build -t "asia-south1-docker.pkg.dev/rare-cubist-450012-v1/python-repo/test:${{ github.sha }}" ./
             docker push "asia-south1-docker.pkg.dev/rare-cubist-450012-v1/python-repo/test:${{ github.sha }}"