name: hello-world
run-name: docker-build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: echo secret
        env: 
          ARTIFACTORY_JSON: "${{ secrets.ARTIFACTORY_JSON }}"
        run: echo ${ARTIFACTORY_JSON}

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ secrets.ARTIFACTORY_JSON }}'
          registry: 'asia-south1-docker.pkg.dev'
          
          
      - name: Docker Login
        env:
          ARTIFACTORY_JSON: "${{ secrets.ARTIFACTORY_JSON }}"
        run: echo ${ARTIFACTORY_JSON} | docker login -u _json_key_base64 --password-stdin https://asia-south1-docker.pkg.dev
