name: hello-world
run-name: docker-build
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: echo secret
        env: 
          ARTIFACTORY_JSON: "${{ secrets.ARTIFACTORY_JSON }}"
        run: echo ${ARTIFACTORY_JSON}

      - name: Login to GCR
        uses: docker/login-action@v3
        env: 
          ARTIFACTORY_JSON: "${{ secrets.ARTIFACTORY_JSON }}"
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.ARTIFACTORY_JSON }}
        
      - name: Docker Login
        env: 
          ARTIFACTORY_JSON: "${{ secrets.ARTIFACTORY_JSON }}"
        run: |- 
             echo ${ARTIFACTORY_JSON}  docker login -u _json_key --password-stdin https://asia-south1-docker.pkg.dev
             
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push Container
        run: |- 
             docker build -t "asia-south1-docker.pkg.dev/python-repo/test:${{ github.sha }}" ./
             docker push "https://asia-south1-docker.pkg.dev/python-repo/test:${{ github.sha }}"
             